---
name: CI
on: push
jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
