---
name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
          yamllint_comment: true
  deploy:
    runs-on: ubuntu
    container: 
      image: cytopia/ansible:2.10
    steps:
      - uses: actions/checkout@v2
      - name: echo
        env:
          ANSIBLE_VAULT: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          echo $ANSIBLE_VAULT
