---
name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
          yamllint_comment: true
  deploy:
    runs-on: ubuntu
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: staging.yml
          requirements: ./collections/requirements.yml
          directory: ./
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            -i inventory/dcnm
